apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: ssarno31/google-hello-app
        ports:
        - containerPort: 80

